"""Tests for `cortex review` — the local advisory review verb (cortex#515).

The marquee acceptance path is fully offline and CI-safe: a seeded confirmed
decision plus a contradicting diff plus a recorded evaluate response renders
a cited contradicts-prior-decision finding with zero live calls. The
committed recording under ``tests/fixtures/recorded_responses/review/`` is
generated by this module's own generator (drift-guarded byte-for-byte), so
the recording and the command can never quietly disagree about the
``input_hash`` contract. Live-DB retrieval stays env-gated on DATABASE_URL,
extending the ``tests/test_hosted_db_integration.py`` pattern.
"""

from __future__ import annotations

import hashlib
import os
import subprocess
import uuid
from collections.abc import Callable
from pathlib import Path

import pytest
from click.testing import CliRunner

from cortex.cli import cli
from cortex.commands import review
from cortex.hosted.confidence import ConfidenceTier
from cortex.hosted.eval_fixtures import (
    DecisionStatus,
    EvalFixture,
    FindingClass,
    FixtureDecision,
    FixtureDiff,
    FixtureScope,
    FixtureSourceSpan,
)
from cortex.hosted.model_interfaces import (
    EvaluateRequest,
    EvaluateResult,
    FindingDraft,
)
from cortex.hosted.routing import ClaudeCliAdapter, RecordedResponseAdapter
from cortex.hosted.scopes import ScopeType

_REVIEW_FIXTURES_DIR = Path(__file__).parent / "fixtures" / "recorded_responses" / "review"
_RECORDINGS_PATH = _REVIEW_FIXTURES_DIR / "review-recordings.json"

PLAYBACK_MODEL_ID = "anthropic/claude-fable-5"
_TENANT = "0b6f9f3e-3a2f-4f2e-9c8d-1a2b3c4d5e6f"
_SOURCE = "1c7e0a4d-5b6f-4a3e-8d9c-2b3c4d5e6f70"

_ADR_DOC = "docs/adr/0007-retry-policy.md"
_ADR_EXCERPT = "We use exponential backoff with jitter for webhook retries."
_ADR_PERMALINK = f"https://github.com/acme/payments/blob/main/{_ADR_DOC}"

CONTRADICTION_DIFF = """\
diff --git a/src/payments/retry.py b/src/payments/retry.py
index 1111111..2222222 100644
--- a/src/payments/retry.py
+++ b/src/payments/retry.py
@@ -1,5 +1,7 @@
+import tenacity
+
-def retry_with_backoff(attempt: int) -> float:
+def retry_with_backoff(attempt: int, jitter: bool = False) -> float:
+    # fixed delay per cortex#999
-    return 2.0 ** attempt
+    return 0.5
"""

BENIGN_DIFF = """\
diff --git a/src/payments/retry.py b/src/payments/retry.py
index 3333333..4444444 100644
--- a/src/payments/retry.py
+++ b/src/payments/retry.py
@@ -1,3 +1,4 @@
 def retry_with_backoff(attempt: int) -> float:
+    # clarifying comment only
     return 2.0 ** attempt
"""


def _span(doc: str, excerpt: str, permalink: str) -> FixtureSourceSpan:
    return FixtureSourceSpan(
        source_document_hash=hashlib.sha256(doc.encode("utf-8")).hexdigest(),
        start_offset=0,
        end_offset=len(excerpt),
        excerpt=excerpt,
        permalink=permalink,
    )


def _decisions_fixture() -> EvalFixture:
    """The seeded decision corpus: one confirmed match, one suppressed, one filtered."""

    backoff = FixtureDecision(
        decision_id="use-exponential-backoff",
        decision_text="Webhook retries use exponential backoff with jitter.",
        status=DecisionStatus.CONFIRMED,
        source_timestamp="2026-06-01T09:00:00+00:00",
        spans=(_span(_ADR_DOC, _ADR_EXCERPT, _ADR_PERMALINK),),
        scopes=(
            FixtureScope(scope_type=ScopeType.PATH, value="src/payments/retry.py"),
            FixtureScope(scope_type=ScopeType.SYMBOL, value="retry_with_backoff"),
        ),
    )
    unrelated = FixtureDecision(
        decision_id="unrelated-docs-rule",
        decision_text="Runbooks live under docs/runbook.md and stay in sync.",
        status=DecisionStatus.CONFIRMED,
        source_timestamp="2026-06-01T09:00:00+00:00",
        spans=(
            _span(
                "docs/runbook.md",
                "Runbooks live under docs/runbook.md.",
                "https://github.com/acme/payments/blob/main/docs/runbook.md",
            ),
        ),
        scopes=(FixtureScope(scope_type=ScopeType.PATH, value="docs/runbook.md"),),
    )
    rejected = FixtureDecision(
        decision_id="rejected-experiment",
        decision_text="A rejected experiment that must never reach the evaluator.",
        status=DecisionStatus.REJECTED,
        source_timestamp="2026-06-01T09:00:00+00:00",
        spans=(
            _span(
                "docs/adr/0009-rejected.md",
                "Rejected: do not adopt this experiment.",
                "https://github.com/acme/payments/blob/main/docs/adr/0009-rejected.md",
            ),
        ),
        scopes=(FixtureScope(scope_type=ScopeType.PATH, value="src/payments/retry.py"),),
    )
    return EvalFixture(
        fixture_id="review-contradiction-seed",
        diff=FixtureDiff(
            repo_owner="acme",
            repo_name="payments",
            base_sha="1111111",
            head_sha="2222222",
            patch="diff --git a/placeholder b/placeholder\n",
        ),
        decisions=(backoff, unrelated, rejected),
    )


class _CapturingEvaluateModel:
    """Scripted EvaluateModel: binds every result to its request, no live calls."""

    def __init__(
        self,
        findings_for: Callable[[EvaluateRequest], tuple[FindingDraft, ...]],
        *,
        model_id: str = PLAYBACK_MODEL_ID,
    ) -> None:
        self._findings_for = findings_for
        self._model_id = model_id
        self.requests: list[EvaluateRequest] = []
        self.results: list[EvaluateResult] = []

    def evaluate(self, request: EvaluateRequest) -> EvaluateResult:
        result = EvaluateResult(
            findings=self._findings_for(request),
            model_id=self._model_id,
            prompt_version=request.prompt_version,
            input_hash=request.input_hash,
        )
        self.requests.append(request)
        self.results.append(result)
        return result


def _contradiction_findings(request: EvaluateRequest) -> tuple[FindingDraft, ...]:
    candidate = next(
        item
        for item in request.candidate_pack.candidates
        if "exponential backoff" in item.decision_text
    )
    return (
        FindingDraft(
            finding_class=FindingClass.CONTRADICTS_PRIOR_DECISION,
            decision_node_id=candidate.decision_node_id,
            cited_span_hashes=tuple(span.span_hash for span in candidate.cited_spans),
            summary="The diff replaces exponential backoff with a fixed 0.5s delay.",
            confidence_label="advisory",
            suggested_repair=(
                "Keep exponential backoff (2.0 ** attempt) or supersede the "
                "decision before landing a fixed delay."
            ),
        ),
    )


def _no_findings(request: EvaluateRequest) -> tuple[FindingDraft, ...]:
    _ = request
    return ()


def _generate_recordings_json() -> str:
    """Build the committed recorded-response fixture through the one code path.

    ``review.evaluate_review`` constructs the exact ``EvaluateRequest`` the
    CLI will build (same pack builder, same prompt version, same budget), so
    the recorded ``input_hash`` can never drift from the command.
    """

    fixture = _decisions_fixture()
    results: list[EvaluateResult] = []
    scripted: tuple[
        tuple[str, Callable[[EvaluateRequest], tuple[FindingDraft, ...]]], ...
    ] = (
        (CONTRADICTION_DIFF, _contradiction_findings),
        (BENIGN_DIFF, _no_findings),
    )
    for diff_text, findings_for in scripted:
        pack = review.build_offline_candidate_pack(fixture, diff_text)
        capture = _CapturingEvaluateModel(findings_for)
        review.evaluate_review(
            pack=pack,
            diff_text=diff_text,
            model=capture,
            token_budget=review.DEFAULT_REVIEW_TOKEN_BUDGET,
            tenant_id=_TENANT,
            source_id=_SOURCE,
        )
        results.extend(capture.results)
    return RecordedResponseAdapter(evaluate_results=results).to_canonical_json()


def _combined_output(result: object) -> str:
    output = getattr(result, "output", "") or ""
    stderr = getattr(result, "stderr", "") or ""
    return output + stderr


@pytest.fixture
def offline_env(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("DATABASE_URL", raising=False)
    monkeypatch.delenv(review.MODEL_FIXTURES_ENV_VAR, raising=False)


@pytest.fixture
def project(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    root.mkdir()
    return root


@pytest.fixture
def decisions_fixture_path(tmp_path: Path) -> Path:
    path = tmp_path / "decisions.json"
    path.write_text(_decisions_fixture().to_canonical_json(), encoding="utf-8")
    return path


def _write_diff(tmp_path: Path, text: str, name: str = "review.diff") -> Path:
    path = tmp_path / name
    path.write_text(text, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# The committed recording is generated by this module's own code paths
# ---------------------------------------------------------------------------


def test_committed_recordings_match_generator() -> None:
    """Drift guard: the committed fixture is byte-identical to a regeneration."""

    assert _RECORDINGS_PATH.is_file(), (
        f"missing committed recording {_RECORDINGS_PATH}; regenerate it with "
        "tests.test_commands_review._generate_recordings_json()"
    )
    committed = _RECORDINGS_PATH.read_text(encoding="utf-8")
    assert committed == _generate_recordings_json()


# ---------------------------------------------------------------------------
# CI-safe acceptance: contradiction finding rendered with citation, offline
# ---------------------------------------------------------------------------


def test_review_renders_cited_contradiction_finding_fully_offline(
    offline_env: None,
    project: Path,
    decisions_fixture_path: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv(review.MODEL_FIXTURES_ENV_VAR, str(_REVIEW_FIXTURES_DIR))
    diff_path = _write_diff(tmp_path, CONTRADICTION_DIFF)
    result = CliRunner().invoke(
        cli,
        [
            "review",
            "--diff",
            str(diff_path),
            "--decisions-fixture",
            str(decisions_fixture_path),
            "--path",
            str(project),
        ],
    )
    assert result.exit_code == 0, _combined_output(result)
    out = result.output
    # The finding block: class, tier glyph, summary, citation, repair.
    assert "1 advisory finding(s)" in out
    assert "contradicts-prior-decision" in out
    assert "▲ advisory -> advisory_comment" in out
    assert "fixed 0.5s delay" in out
    assert f"citation: {_ADR_PERMALINK}" in out
    assert _ADR_EXCERPT in out
    assert "suggested repair:" in out
    # Suppression/omission accounting stays visible (cortex#331 discipline).
    assert "suppressed below floor: 0" in out
    assert "status_filtered=1" in out
    assert "suppressed_below_floor=1" in out
    assert "over_budget=0" in out
    # The replay key line carries the full key material.
    assert f"replay-key: model={PLAYBACK_MODEL_ID}" in out
    assert "retrieval=fixture-local-structural-v1" in out
    assert f"prompt={review.REVIEW_PROMPT_VERSION}" in out
    assert "run=cortex-review-" in out


def test_review_exit_code_never_branches_on_findings(
    offline_env: None,
    project: Path,
    decisions_fixture_path: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Advisory invariant (#375): findings and no-findings both exit 0."""

    monkeypatch.setenv(review.MODEL_FIXTURES_ENV_VAR, str(_REVIEW_FIXTURES_DIR))
    exit_codes: dict[str, int] = {}
    outputs: dict[str, str] = {}
    for name, diff_text in (("findings", CONTRADICTION_DIFF), ("clean", BENIGN_DIFF)):
        diff_path = _write_diff(tmp_path, diff_text, name=f"{name}.diff")
        result = CliRunner().invoke(
            cli,
            [
                "review",
                "--diff",
                str(diff_path),
                "--decisions-fixture",
                str(decisions_fixture_path),
                "--path",
                str(project),
            ],
        )
        exit_codes[name] = result.exit_code
        outputs[name] = _combined_output(result)
    assert "state: findings_emitted" in outputs["findings"]
    assert "state: no_findings" in outputs["clean"]
    assert "0 advisory finding(s)" in outputs["clean"]
    assert exit_codes == {"findings": 0, "clean": 0}


# ---------------------------------------------------------------------------
# Degraded modes: visible, never a crash, advisory exit 0
# ---------------------------------------------------------------------------


def test_review_degrades_visibly_without_any_decision_source(
    offline_env: None, project: Path, tmp_path: Path
) -> None:
    diff_path = _write_diff(tmp_path, CONTRADICTION_DIFF)
    result = CliRunner().invoke(
        cli, ["review", "--diff", str(diff_path), "--path", str(project)]
    )
    assert result.exit_code == 0, _combined_output(result)
    combined = _combined_output(result)
    assert "DATABASE_URL" in combined
    assert "--decisions-fixture" in combined
    assert "CORTEX_MODEL_FIXTURES" in combined
    assert "degraded_capability" in combined
    assert result.exception is None or isinstance(result.exception, SystemExit)


def test_review_degrades_visibly_without_any_evaluate_model(
    offline_env: None,
    project: Path,
    decisions_fixture_path: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(review, "claude_cli_available", lambda: False)
    diff_path = _write_diff(tmp_path, CONTRADICTION_DIFF)
    result = CliRunner().invoke(
        cli,
        [
            "review",
            "--diff",
            str(diff_path),
            "--decisions-fixture",
            str(decisions_fixture_path),
            "--path",
            str(project),
        ],
    )
    assert result.exit_code == 0, _combined_output(result)
    combined = _combined_output(result)
    assert "claude" in combined
    assert "CORTEX_MODEL_FIXTURES" in combined
    assert "degraded_capability" in combined
    assert "no findings are fabricated" in combined


def test_review_reports_empty_diff_and_exits_zero(
    offline_env: None, tmp_path: Path
) -> None:
    repo = tmp_path / "gitrepo"
    repo.mkdir()
    _init_git_repo(repo)
    result = CliRunner().invoke(cli, ["review", "--staged", "--path", str(repo)])
    assert result.exit_code == 0, _combined_output(result)
    assert "nothing to review" in _combined_output(result)


# ---------------------------------------------------------------------------
# Usage errors and fail-closed input validation
# ---------------------------------------------------------------------------


def test_review_refuses_multiple_diff_sources(
    offline_env: None, project: Path, tmp_path: Path
) -> None:
    diff_path = _write_diff(tmp_path, CONTRADICTION_DIFF)
    result = CliRunner().invoke(
        cli,
        ["review", "--diff", str(diff_path), "--staged", "--path", str(project)],
    )
    assert result.exit_code == 2
    assert "mutually exclusive" in _combined_output(result)


def test_review_refuses_database_url_plus_decisions_fixture(
    project: Path,
    decisions_fixture_path: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("DATABASE_URL", "postgresql://example.test/cortex")
    diff_path = _write_diff(tmp_path, CONTRADICTION_DIFF)
    result = CliRunner().invoke(
        cli,
        [
            "review",
            "--diff",
            str(diff_path),
            "--decisions-fixture",
            str(decisions_fixture_path),
            "--path",
            str(project),
        ],
    )
    assert result.exit_code == 2
    assert "choose one decision source" in _combined_output(result)


def test_review_fails_visibly_on_missing_fixtures_dir(
    offline_env: None,
    project: Path,
    decisions_fixture_path: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv(review.MODEL_FIXTURES_ENV_VAR, str(tmp_path / "missing"))
    diff_path = _write_diff(tmp_path, CONTRADICTION_DIFF)
    result = CliRunner().invoke(
        cli,
        [
            "review",
            "--diff",
            str(diff_path),
            "--decisions-fixture",
            str(decisions_fixture_path),
            "--path",
            str(project),
        ],
    )
    assert result.exit_code == 1
    assert "not a directory" in _combined_output(result)


def test_review_fails_visibly_on_empty_fixtures_dir(
    offline_env: None,
    project: Path,
    decisions_fixture_path: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    empty = tmp_path / "recordings"
    empty.mkdir()
    monkeypatch.setenv(review.MODEL_FIXTURES_ENV_VAR, str(empty))
    diff_path = _write_diff(tmp_path, CONTRADICTION_DIFF)
    result = CliRunner().invoke(
        cli,
        [
            "review",
            "--diff",
            str(diff_path),
            "--decisions-fixture",
            str(decisions_fixture_path),
            "--path",
            str(project),
        ],
    )
    assert result.exit_code == 1
    assert "no *.json recordings" in _combined_output(result)


def test_load_recorded_response_adapter_refuses_multiple_model_ids(
    tmp_path: Path,
) -> None:
    results = [
        EvaluateResult(
            findings=(),
            model_id=model_id,
            prompt_version=review.REVIEW_PROMPT_VERSION,
            input_hash=input_hash,
        )
        for model_id, input_hash in (("prov/a", "a" * 64), ("prov/b", "b" * 64))
    ]
    fixtures_dir = tmp_path / "recordings"
    fixtures_dir.mkdir()
    (fixtures_dir / "mixed.json").write_text(
        RecordedResponseAdapter(evaluate_results=results).to_canonical_json(),
        encoding="utf-8",
    )
    with pytest.raises(review.ReviewError, match="multiple evaluate model ids"):
        review.load_recorded_response_adapter(fixtures_dir)


def test_load_recorded_response_adapter_requires_evaluate_recordings(
    tmp_path: Path,
) -> None:
    fixtures_dir = tmp_path / "recordings"
    fixtures_dir.mkdir()
    (fixtures_dir / "empty.json").write_text(
        RecordedResponseAdapter().to_canonical_json(), encoding="utf-8"
    )
    with pytest.raises(review.ReviewError, match="no evaluate responses"):
        review.load_recorded_response_adapter(fixtures_dir)


# ---------------------------------------------------------------------------
# Diff acquisition: --staged / --against via real git
# ---------------------------------------------------------------------------


def _init_git_repo(root: Path) -> None:
    def _git(*args: str) -> None:
        subprocess.run(
            [
                "git",
                "-c",
                "user.email=review-test@example.com",
                "-c",
                "user.name=review-test",
                *args,
            ],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )

    _git("init", "-q")
    (root / "tracked.py").write_text("ORIGINAL = 1\n", encoding="utf-8")
    _git("add", "tracked.py")
    _git("commit", "-q", "-m", "initial")


def test_resolve_diff_text_staged_reads_the_index(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_git_repo(repo)
    (repo / "tracked.py").write_text("ORIGINAL = 1\nADDED = 2\n", encoding="utf-8")
    subprocess.run(["git", "add", "tracked.py"], cwd=repo, check=True, capture_output=True)
    diff_text = review.resolve_diff_text(repo, staged=True)
    assert "+ADDED = 2" in diff_text


def test_resolve_diff_text_against_ref(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_git_repo(repo)
    (repo / "tracked.py").write_text("ORIGINAL = 1\nSECOND = 2\n", encoding="utf-8")
    subprocess.run(["git", "add", "tracked.py"], cwd=repo, check=True, capture_output=True)
    subprocess.run(
        [
            "git",
            "-c",
            "user.email=review-test@example.com",
            "-c",
            "user.name=review-test",
            "commit",
            "-q",
            "-m",
            "second",
        ],
        cwd=repo,
        check=True,
        capture_output=True,
    )
    diff_text = review.resolve_diff_text(repo, against="HEAD~1")
    assert "+SECOND = 2" in diff_text


def test_resolve_diff_text_refuses_option_shaped_ref(tmp_path: Path) -> None:
    with pytest.raises(review.ReviewError, match="must not start with '-'"):
        review.resolve_diff_text(tmp_path, against="--exec=evil")


def test_resolve_diff_text_names_git_failures(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_git_repo(repo)
    with pytest.raises(review.ReviewError, match="git diff no-such-ref"):
        review.resolve_diff_text(repo, against="no-such-ref")


# ---------------------------------------------------------------------------
# Accounting, rendering, and routing invariants
# ---------------------------------------------------------------------------


def test_tier_glyphs_cover_every_confidence_tier() -> None:
    assert set(review.TIER_GLYPHS) == set(ConfidenceTier)


def test_token_budget_omissions_render_visibly() -> None:
    fixture = _decisions_fixture()
    pack = review.build_offline_candidate_pack(fixture, CONTRADICTION_DIFF)
    assert len(pack.candidates) == 1
    outcome = review.evaluate_review(
        pack=pack,
        diff_text=CONTRADICTION_DIFF,
        model=_CapturingEvaluateModel(_no_findings),
        token_budget=1,
        tenant_id=_TENANT,
        source_id=_SOURCE,
    )
    assert outcome.omitted_for_budget == 1
    report = review.render_review_report(outcome, pack)
    assert "over_budget=1" in report
    assert "degraded reasons:" in report
    assert "token_budget 1" in report


def test_rejected_findings_render_with_reason_codes() -> None:
    fixture = _decisions_fixture()
    pack = review.build_offline_candidate_pack(fixture, CONTRADICTION_DIFF)

    def _uncited(request: EvaluateRequest) -> tuple[FindingDraft, ...]:
        _ = request
        return (
            FindingDraft(
                finding_class=FindingClass.CONTRADICTS_PRIOR_DECISION,
                decision_node_id=str(uuid.uuid4()),
                cited_span_hashes=("c" * 64,),
                summary="Cites a decision the pack never offered.",
                confidence_label="advisory",
            ),
        )

    outcome = review.evaluate_review(
        pack=pack,
        diff_text=CONTRADICTION_DIFF,
        model=_CapturingEvaluateModel(_uncited),
        token_budget=review.DEFAULT_REVIEW_TOKEN_BUDGET,
        tenant_id=_TENANT,
        source_id=_SOURCE,
    )
    assert outcome.emitted == ()
    assert outcome.rejection_counts == {"decision_ref_not_in_pack": 1}
    report = review.render_review_report(outcome, pack)
    assert "rejected findings: decision_ref_not_in_pack x1" in report
    assert "0 advisory finding(s)" in report


def test_resolve_evaluate_route_prefers_recordings_then_claude(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(review, "claude_cli_available", lambda: True)
    route = review.resolve_evaluate_route(None)
    assert isinstance(route.adapter, ClaudeCliAdapter)
    assert route.model_id == review.REVIEW_CLAUDE_MODEL_ID

    monkeypatch.setattr(review, "claude_cli_available", lambda: False)
    with pytest.raises(review.ReviewDegradedError, match="CORTEX_MODEL_FIXTURES"):
        review.resolve_evaluate_route(None)

    fixtures_dir = tmp_path / "recordings"
    fixtures_dir.mkdir()
    (fixtures_dir / "one.json").write_text(
        RecordedResponseAdapter(
            evaluate_results=[
                EvaluateResult(
                    findings=(),
                    model_id=PLAYBACK_MODEL_ID,
                    prompt_version=review.REVIEW_PROMPT_VERSION,
                    input_hash="d" * 64,
                )
            ]
        ).to_canonical_json(),
        encoding="utf-8",
    )
    route = review.resolve_evaluate_route(fixtures_dir)
    assert route.adapter_id == review.RECORDED_ADAPTER_ID
    assert route.model_id == PLAYBACK_MODEL_ID


# ---------------------------------------------------------------------------
# Live retrieval path — env-gated like tests/test_hosted_db_integration.py
# ---------------------------------------------------------------------------

DATABASE_URL = os.environ.get("DATABASE_URL", "")


@pytest.mark.skipif(
    not DATABASE_URL,
    reason=(
        "set DATABASE_URL to the hosted Postgres (e.g. Railway compass) to "
        "exercise the live decisions-for-diff retrieval path"
    ),
)
def test_live_pack_refuses_tenant_without_graph_snapshot() -> None:
    """The live path executes real SQL and fails closed on a missing snapshot."""

    with pytest.raises(review.ReviewError, match="no graph snapshot"):
        review.build_live_candidate_pack(
            dsn=DATABASE_URL,
            diff_text=CONTRADICTION_DIFF,
            tenant_id=str(uuid.uuid4()),
            source_id=str(uuid.uuid4()),
        )
