"""Tests for the stateless GitHub PR review handler (cortex#537).

The default-tier reviewer: fetch the repo's decision files and PR diff over
the installation token, derive+scope the pack in memory, evaluate, render the
advisory comment, and — by default — dry-run instead of posting. Stateless:
nothing about the customer's decisions or code is persisted (no database is
touched on the review path at all).

The marquee acceptance path is fully offline: a fake
``GithubInstallationClient`` serves a canned ``CLAUDE.md`` + a doctrine
decision + a contradicting diff, a recorded evaluate response (committed under
``tests/fixtures/recorded_responses/stateless_review/`` and generated by this
module's own code path so the ``input_hash`` can never drift) plays the model,
and the render produces a cited ``contradicts-prior-decision`` comment with
zero post calls in dry-run.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from cortex.hosted import stateless_review
from cortex.hosted.eval_fixtures import FindingClass
from cortex.hosted.github_app_auth import (
    ChangedFile,
    DirectoryEntry,
    GithubApiError,
)
from cortex.hosted.github_comment import extract_marker
from cortex.hosted.jobs import ClaimedJob
from cortex.hosted.model_interfaces import (
    EvaluateRequest,
    EvaluateResult,
    FindingDraft,
)
from cortex.hosted.routing import RecordedResponseAdapter
from cortex.hosted.stateless_review import (
    PullRequestEvent,
    ReviewHandlerConfig,
    StatelessReviewError,
    build_review_handler,
    build_review_registry,
    parse_pull_request_payload,
    run_stateless_review,
)

_STATELESS_FIXTURES_DIR = (
    Path(__file__).parent / "fixtures" / "recorded_responses" / "stateless_review"
)
_RECORDINGS_PATH = _STATELESS_FIXTURES_DIR / "stateless-review-recordings.json"

PLAYBACK_MODEL_ID = "anthropic/claude-fable-5"
_INSTALLATION_ID = "424242"
_OWNER = "acme"
_REPO = "widgets"
_PR_NUMBER = 7
_BASE_SHA = "1111111"
_HEAD_SHA = "2222222"
_FIXED_TIME = datetime(2026, 6, 10, 12, 0, 0, tzinfo=UTC)

# A confirmed decision: compose-by-file-contract, scoped to the file the diff
# touches. The contradicting diff adds the forbidden import to that file.
CLAUDE_MD = """\
# Acme Widgets

## Engineering Principles (HARD REQUIREMENTS)

- **Compose by file contract, not code.** Do not `import sentinel` inside \
`src/widgets/core.py`; integration with sibling tools is by file contract only.
- **No band-aids.** Fix the root cause, not the symptom.
"""

DOCTRINE_MD = """\
# 0001 — Webhook retry policy

**Status:** Accepted
**Date:** 2026-06-01

## Context

Webhook delivery was flaky under load.

## Decision

Webhook retries in `src/widgets/retry.py` use exponential backoff with jitter.
"""

CONTRADICTION_DIFF = """\
diff --git a/src/widgets/core.py b/src/widgets/core.py
index 1111111..2222222 100644
--- a/src/widgets/core.py
+++ b/src/widgets/core.py
@@ -1,3 +1,5 @@
+import sentinel
+
 def run() -> int:
     return 1
"""

BENIGN_DIFF = """\
diff --git a/src/widgets/core.py b/src/widgets/core.py
index 3333333..4444444 100644
--- a/src/widgets/core.py
+++ b/src/widgets/core.py
@@ -1,2 +1,3 @@
 def run() -> int:
+    # clarifying comment only
     return 1
"""

UNRELATED_DIFF = """\
diff --git a/README.md b/README.md
index 5555555..6666666 100644
--- a/README.md
+++ b/README.md
@@ -1,1 +1,2 @@
 # Acme Widgets
+A widgets project.
"""


# ---------------------------------------------------------------------------
# A fake installation client: serves a canned repo, records every call
# ---------------------------------------------------------------------------


class FakeInstallationClient:
    """A canned GitHub repo served entirely from memory; records writes.

    Files and directory listings are keyed by ``(path, ref)`` so the test can
    assert the reviewer fetched the *base* SHA. Posting and updating record
    onto ``posted`` / ``updated`` so a dry-run can be asserted to have made
    zero writes, and an idempotent re-run can be asserted to update not
    duplicate.
    """

    def __init__(
        self,
        *,
        files: Mapping[tuple[str, str], str],
        directories: Mapping[tuple[str, str], tuple[DirectoryEntry, ...]],
        diff: str,
    ) -> None:
        self._files = dict(files)
        self._directories = dict(directories)
        self._diff = diff
        self.comments: list[dict[str, Any]] = []
        self.posted: list[dict[str, Any]] = []
        self.updated: list[dict[str, Any]] = []
        self.diff_calls: list[tuple[str, str, int]] = []
        self._next_comment_id = 1000

    def get_pull_request_diff(self, owner: str, repo: str, pr_number: int) -> str:
        self.diff_calls.append((owner, repo, pr_number))
        return self._diff

    def get_file_contents(self, owner: str, repo: str, path: str, ref: str) -> bytes | None:
        content = self._files.get((path, ref))
        if content is None:
            return None
        return content.encode("utf-8")

    def list_directory(
        self, owner: str, repo: str, path: str, ref: str
    ) -> tuple[DirectoryEntry, ...]:
        return self._directories.get((path, ref), ())

    def list_pull_request_files(
        self, owner: str, repo: str, pr_number: int
    ) -> tuple[ChangedFile, ...]:  # pragma: no cover - reviewer uses the diff
        return ()

    def list_issue_comments(
        self, owner: str, repo: str, issue_number: int
    ) -> tuple[Mapping[str, Any], ...]:
        return tuple(self.comments)

    def post_issue_comment(
        self, owner: str, repo: str, issue_number: int, body: str
    ) -> Mapping[str, Any]:
        comment_id = self._next_comment_id
        self._next_comment_id += 1
        record = {
            "id": comment_id,
            "html_url": f"https://github.com/{owner}/{repo}/pull/{issue_number}#c{comment_id}",
            "body": body,
        }
        self.comments.append(record)
        self.posted.append(record)
        return {"id": record["id"], "html_url": record["html_url"]}

    def update_issue_comment(
        self, owner: str, repo: str, comment_id: int, body: str
    ) -> Mapping[str, Any]:
        for record in self.comments:
            if record["id"] == comment_id:
                record["body"] = body
                self.updated.append(record)
                return {"id": comment_id, "html_url": record["html_url"]}
        raise GithubApiError(f"no comment {comment_id} to update")


def _full_repo_client(diff: str = CONTRADICTION_DIFF) -> FakeInstallationClient:
    doctrine_path = ".cortex/doctrine/0001-retry.md"
    return FakeInstallationClient(
        files={
            ("CLAUDE.md", _BASE_SHA): CLAUDE_MD,
            (doctrine_path, _BASE_SHA): DOCTRINE_MD,
        },
        directories={
            (".cortex/doctrine", _BASE_SHA): (DirectoryEntry(path=doctrine_path, type="file"),),
            (".cortex/plans", _BASE_SHA): (),
        },
        diff=diff,
    )


def _empty_repo_client(diff: str = CONTRADICTION_DIFF) -> FakeInstallationClient:
    """A repo with no CLAUDE.md, no AGENTS.md, no .cortex/ — the degraded case."""

    return FakeInstallationClient(files={}, directories={}, diff=diff)


# ---------------------------------------------------------------------------
# Scripted + recorded models
# ---------------------------------------------------------------------------


class _CapturingEvaluateModel:
    """Scripted EvaluateModel binding each result to its request; no live call."""

    def __init__(
        self,
        findings_for: Callable[[EvaluateRequest], tuple[FindingDraft, ...]],
        *,
        model_id: str = PLAYBACK_MODEL_ID,
    ) -> None:
        self._findings_for = findings_for
        self._model_id = model_id
        self.results: list[EvaluateResult] = []

    def evaluate(self, request: EvaluateRequest) -> EvaluateResult:
        result = EvaluateResult(
            findings=self._findings_for(request),
            model_id=self._model_id,
            prompt_version=request.prompt_version,
            input_hash=request.input_hash,
        )
        self.results.append(result)
        return result


def _contradiction_findings(request: EvaluateRequest) -> tuple[FindingDraft, ...]:
    candidate = next(
        item for item in request.candidate_pack.candidates if "file contract" in item.decision_text
    )
    return (
        FindingDraft(
            finding_class=FindingClass.CONTRADICTS_PRIOR_DECISION,
            decision_node_id=candidate.decision_node_id,
            cited_span_hashes=tuple(span.span_hash for span in candidate.cited_spans),
            summary=(
                "The diff adds `import sentinel` to src/widgets/core.py, directly "
                "reversing the confirmed compose-by-file-contract decision."
            ),
            confidence_label="advisory",
            suggested_repair=(
                "Remove the `import sentinel` dependency and integrate by file "
                "contract, or supersede the decision before landing this."
            ),
        ),
    )


def _no_findings(request: EvaluateRequest) -> tuple[FindingDraft, ...]:
    _ = request
    return ()


class _RoutedRecordedModel:
    """Wraps the committed RecordedResponseAdapter as an EvaluateModel.

    The adapter plays back by ``(task, input_hash)`` and never falls back to a
    live call; this thin shim presents the ``evaluate(request)`` protocol the
    handler injects, with the route identity the recording was made under.
    """

    def __init__(self) -> None:
        self._adapter = RecordedResponseAdapter.from_json(
            _RECORDINGS_PATH.read_text(encoding="utf-8")
        )

    def evaluate(self, request: EvaluateRequest) -> EvaluateResult:
        from cortex.hosted.routing import RouteConfig, TaskKind

        route = RouteConfig(
            task_kind=TaskKind.EVALUATE,
            model_id=PLAYBACK_MODEL_ID,
            adapter_id="recorded-responses",
        )
        outcome = self._adapter.run_evaluate(request, route)
        assert isinstance(outcome.result, EvaluateResult)
        return outcome.result


# ---------------------------------------------------------------------------
# Recorded fixture generation (through this module's own code path)
# ---------------------------------------------------------------------------


def _payload(diff_marker: str = "pull_request") -> dict[str, Any]:
    _ = diff_marker
    return {
        "event": "pull_request",
        "body": {
            "action": "opened",
            "installation": {"id": int(_INSTALLATION_ID)},
            "repository": {"name": _REPO, "owner": {"login": _OWNER}},
            "pull_request": {
                "number": _PR_NUMBER,
                "base": {"sha": _BASE_SHA},
                "head": {"sha": _HEAD_SHA},
            },
        },
    }


def _generate_recordings_json() -> str:
    """Build the committed recording through ``run_stateless_review`` itself.

    The exact pack/diff/prompt/budget the handler builds are the ones the
    capturing model sees, so the recorded ``input_hash`` is byte-identical to
    what playback will key on. Both the contradiction and benign diffs are
    recorded so the offline suite can exercise findings and no-findings.
    """

    results: list[EvaluateResult] = []
    scripted: tuple[tuple[str, Callable[[EvaluateRequest], tuple[FindingDraft, ...]]], ...] = (
        (CONTRADICTION_DIFF, _contradiction_findings),
        (BENIGN_DIFF, _no_findings),
        (UNRELATED_DIFF, _no_findings),
    )
    for diff_text, findings_for in scripted:
        client = _full_repo_client(diff_text)
        capture = _CapturingEvaluateModel(findings_for)
        run_stateless_review(
            _payload(),
            client=client,
            model=capture,
            config=ReviewHandlerConfig(dry_run=True),
            now=lambda: _FIXED_TIME,
        )
        results.extend(capture.results)
    return RecordedResponseAdapter(evaluate_results=results).to_canonical_json()


def test_committed_recordings_match_generator() -> None:
    """Drift guard: the committed fixture is byte-identical to a regeneration."""

    assert _RECORDINGS_PATH.is_file(), (
        f"missing committed recording {_RECORDINGS_PATH}; regenerate it with "
        "tests.test_hosted_stateless_review._generate_recordings_json()"
    )
    committed = _RECORDINGS_PATH.read_text(encoding="utf-8")
    assert committed == _generate_recordings_json()


# ---------------------------------------------------------------------------
# Payload parsing (fail-closed)
# ---------------------------------------------------------------------------


def test_parse_payload_reads_installation_repo_and_pr() -> None:
    event = parse_pull_request_payload(_payload())
    assert event.installation_id == _INSTALLATION_ID
    assert event.owner == _OWNER
    assert event.repo == _REPO
    assert event.pr_number == _PR_NUMBER
    assert event.base_sha == _BASE_SHA
    assert event.head_sha == _HEAD_SHA


def test_parse_payload_reads_top_level_body_when_unwrapped() -> None:
    """The PR event body may arrive at the top level, not under 'body'."""

    body = _payload()["body"]
    event = parse_pull_request_payload(body)
    assert event.pr_number == _PR_NUMBER


def test_parse_payload_accepts_string_installation_id() -> None:
    payload = _payload()
    payload["body"]["installation"]["id"] = "55"
    assert parse_pull_request_payload(payload).installation_id == "55"


@pytest.mark.parametrize(
    "mutate",
    [
        lambda p: p["body"].pop("installation"),
        lambda p: p["body"].pop("repository"),
        lambda p: p["body"].pop("pull_request"),
        lambda p: p["body"]["repository"].pop("owner"),
        lambda p: p["body"]["pull_request"].pop("base"),
        lambda p: p["body"]["pull_request"].pop("head"),
        lambda p: p["body"]["pull_request"].update({"number": "seven"}),
        lambda p: p["body"]["pull_request"].update({"number": -1}),
        lambda p: p["body"]["repository"]["owner"].update({"login": ""}),
    ],
    ids=[
        "no-installation",
        "no-repository",
        "no-pull_request",
        "no-owner",
        "no-base",
        "no-head",
        "non-int-number",
        "negative-number",
        "blank-owner",
    ],
)
def test_parse_payload_fails_closed_on_malformed_field(
    mutate: Callable[[dict[str, Any]], Any],
) -> None:
    payload = _payload()
    mutate(payload)
    with pytest.raises(StatelessReviewError):
        parse_pull_request_payload(payload)


def test_parse_payload_refuses_non_object() -> None:
    with pytest.raises(StatelessReviewError):
        parse_pull_request_payload([])  # type: ignore[arg-type]


def test_malformed_payload_is_registered_fail_closed() -> None:
    """The error classifies as invalid-input-rejected with a remediation."""

    from cortex.hosted.degradation import (
        DegradationMode,
        classify_failure,
        remediation_for,
    )

    payload = _payload()
    payload["body"].pop("pull_request")
    try:
        parse_pull_request_payload(payload)
    except StatelessReviewError as exc:
        assert classify_failure(exc) is DegradationMode.INVALID_INPUT_REJECTED
    else:  # pragma: no cover - the parse must raise
        pytest.fail("expected StatelessReviewError")
    assert remediation_for("stateless_review_payload_malformed").strip()


# ---------------------------------------------------------------------------
# The acceptance path: cited contradiction comment, dry-run, zero posts
# ---------------------------------------------------------------------------


def test_dry_run_renders_cited_contradiction_and_posts_nothing() -> None:
    client = _full_repo_client(CONTRADICTION_DIFF)
    result = run_stateless_review(
        _payload(),
        client=client,
        model=_RoutedRecordedModel(),
        config=ReviewHandlerConfig(dry_run=True),
        now=lambda: _FIXED_TIME,
    )
    assert result.dry_run is True
    assert result.posted is False
    assert result.finding_count == 1
    assert result.no_decisions is False
    body = result.comment_body
    assert "Contradicts a prior decision" in body
    assert "import sentinel" in body
    # The cited decision resolves to a base-SHA blob permalink (the repo is
    # the store; the citation points back at the customer's own file).
    assert f"blob/{_BASE_SHA}/CLAUDE.md" in body
    # The stable marker carries this PR + head SHA so the poster can update it.
    marker = extract_marker(body)
    assert marker is not None
    assert marker.pr_number == _PR_NUMBER
    assert marker.head_sha == _HEAD_SHA
    # Dry-run made zero writes to GitHub.
    assert client.posted == []
    assert client.updated == []
    # And it fetched the decision baseline at the BASE sha, the diff once.
    assert client.diff_calls == [(_OWNER, _REPO, _PR_NUMBER)]


def test_dry_run_no_findings_on_benign_diff() -> None:
    client = _full_repo_client(BENIGN_DIFF)
    result = run_stateless_review(
        _payload(),
        client=client,
        model=_RoutedRecordedModel(),
        config=ReviewHandlerConfig(dry_run=True),
        now=lambda: _FIXED_TIME,
    )
    assert result.finding_count == 0
    assert result.no_decisions is False
    assert "No contradictions found" in result.comment_body
    assert client.posted == []


# ---------------------------------------------------------------------------
# Posting: idempotent create-then-update by marker
# ---------------------------------------------------------------------------


def test_post_creates_then_updates_on_rerun_same_head_sha() -> None:
    client = _full_repo_client(CONTRADICTION_DIFF)
    config = ReviewHandlerConfig(dry_run=False)
    first = run_stateless_review(
        _payload(),
        client=client,
        model=_RoutedRecordedModel(),
        config=config,
        now=lambda: _FIXED_TIME,
    )
    assert first.posted is True
    assert first.comment_id is not None
    assert len(client.posted) == 1
    assert client.updated == []
    # A re-delivery on the same head SHA finds the marker and UPDATES — never
    # a second comment (idempotent: one comment per (PR, head SHA)).
    second = run_stateless_review(
        _payload(),
        client=client,
        model=_RoutedRecordedModel(),
        config=config,
        now=lambda: _FIXED_TIME,
    )
    assert second.posted is True
    assert second.comment_id == first.comment_id
    assert len(client.posted) == 1
    assert len(client.updated) == 1
    assert len(client.comments) == 1


def test_post_no_decisions_comment_is_idempotent() -> None:
    client = _empty_repo_client(CONTRADICTION_DIFF)
    config = ReviewHandlerConfig(dry_run=False)
    run_stateless_review(_payload(), client=client, model=_RoutedRecordedModel(), config=config)
    run_stateless_review(_payload(), client=client, model=_RoutedRecordedModel(), config=config)
    assert len(client.posted) == 1
    assert len(client.updated) == 1


# ---------------------------------------------------------------------------
# Missing .cortex/ degrades to a visible no-decisions comment, never a crash
# ---------------------------------------------------------------------------


def test_missing_decisions_yields_visible_no_decisions_comment() -> None:
    client = _empty_repo_client(CONTRADICTION_DIFF)
    result = run_stateless_review(
        _payload(),
        client=client,
        model=_RoutedRecordedModel(),
        config=ReviewHandlerConfig(dry_run=True),
        now=lambda: _FIXED_TIME,
    )
    assert result.no_decisions is True
    assert result.finding_count == 0
    body = result.comment_body
    assert "no recorded decisions" in body.lower()
    # The comment still carries the marker so a later real review can update it.
    assert extract_marker(body) is not None
    # No model evaluation ran; no crash.
    assert client.posted == []


def test_no_decisions_when_diff_touches_no_recorded_surface() -> None:
    """Decisions exist but none scope to the changed surface -> no findings."""

    client = _full_repo_client(UNRELATED_DIFF)
    result = run_stateless_review(
        _payload(),
        client=client,
        model=_RoutedRecordedModel(),
        config=ReviewHandlerConfig(dry_run=True),
        now=lambda: _FIXED_TIME,
    )
    # Decisions were found (no_decisions stays False) but the diff touches
    # README.md, which no decision scopes to, so the pack is empty and the
    # comment honestly records nothing matched.
    assert result.no_decisions is False
    assert result.finding_count == 0
    assert "No recorded decisions matched" in result.comment_body


# ---------------------------------------------------------------------------
# Statelessness: the review path touches no database
# ---------------------------------------------------------------------------


def test_review_path_imports_no_database_connection(monkeypatch: pytest.MonkeyPatch) -> None:
    """Invariant: the stateless review never opens a database connection.

    ``cortex.hosted.db.connect`` is the one door to Postgres; if the review
    path called it, this would fire. The whole pipeline runs with it
    booby-trapped and still produces the cited comment — proving the review is
    DB-free (the repo is the store).
    """

    import cortex.hosted.db as db

    def _explode(*_args: Any, **_kwargs: Any) -> Any:
        raise AssertionError("the stateless review path must not touch the database")

    monkeypatch.setattr(db, "connect", _explode)
    client = _full_repo_client(CONTRADICTION_DIFF)
    result = run_stateless_review(
        _payload(),
        client=client,
        model=_RoutedRecordedModel(),
        config=ReviewHandlerConfig(dry_run=True),
        now=lambda: _FIXED_TIME,
    )
    assert result.finding_count == 1


def test_result_mapping_is_content_free_of_decision_graph() -> None:
    """The handler result names a mode and counts, never durable review text."""

    client = _full_repo_client(CONTRADICTION_DIFF)
    result = run_stateless_review(
        _payload(),
        client=client,
        model=_RoutedRecordedModel(),
        config=ReviewHandlerConfig(dry_run=True),
        now=lambda: _FIXED_TIME,
    )
    mapping = result.as_result_mapping()
    assert mapping["review_mode"] == "stateless"
    assert mapping["handled"] is True
    assert mapping["dry_run"] is True
    assert mapping["finding_count"] == 1
    assert "comment_body" not in mapping
    printable = result.as_result_mapping(include_comment_body=True)
    assert "Contradicts a prior decision" in printable["comment_body"]


# ---------------------------------------------------------------------------
# Base-SHA fetch discipline + permalink pinning
# ---------------------------------------------------------------------------


def test_decision_sources_are_fetched_at_base_sha_only() -> None:
    """A decision file present only at HEAD is not fetched (base is the baseline)."""

    doctrine_path = ".cortex/doctrine/0001-retry.md"
    client = FakeInstallationClient(
        files={
            ("CLAUDE.md", _BASE_SHA): CLAUDE_MD,
            (doctrine_path, _BASE_SHA): DOCTRINE_MD,
            # A file only at HEAD must be invisible to the base-SHA fetch.
            ("CLAUDE.md", _HEAD_SHA): "# head only\n",
        },
        directories={
            (".cortex/doctrine", _BASE_SHA): (DirectoryEntry(path=doctrine_path, type="file"),),
            (".cortex/plans", _BASE_SHA): (),
        },
        diff=CONTRADICTION_DIFF,
    )
    sources = stateless_review.fetch_decision_sources(
        client, parse_pull_request_payload(_payload()), ReviewHandlerConfig()
    )
    paths = {source.path for source in sources}
    assert paths == {"CLAUDE.md", doctrine_path}
    for source in sources:
        assert f"/blob/{_BASE_SHA}/" in source.permalink


# ---------------------------------------------------------------------------
# Worker wiring
# ---------------------------------------------------------------------------


def _claimed_job(payload: Mapping[str, Any]) -> ClaimedJob:
    return ClaimedJob(
        job_id="job-1",
        job_type="github.pull_request",
        idempotency_key="delivery-guid-1",
        payload=dict(payload),
        attempts=1,
        max_attempts=5,
    )


def test_build_review_handler_dispatches_through_the_pipeline() -> None:
    client = _full_repo_client(CONTRADICTION_DIFF)
    handler = build_review_handler(
        client_factory=lambda installation_id: client,
        model_resolver=lambda: _RoutedRecordedModel(),
        config=ReviewHandlerConfig(dry_run=True),
    )
    result = handler(_claimed_job(_payload()))
    assert result["review_mode"] == "stateless"
    assert result["finding_count"] == 1
    assert result["dry_run"] is True
    assert client.posted == []


def test_build_review_handler_passes_installation_id_to_factory() -> None:
    seen: list[str] = []

    def factory(installation_id: str) -> FakeInstallationClient:
        seen.append(installation_id)
        return _full_repo_client(CONTRADICTION_DIFF)

    handler = build_review_handler(
        client_factory=factory,
        model_resolver=lambda: _RoutedRecordedModel(),
        config=ReviewHandlerConfig(dry_run=True),
    )
    handler(_claimed_job(_payload()))
    assert seen == [_INSTALLATION_ID]


def test_build_review_handler_skips_disabled_repo_before_client_or_model() -> None:
    checked: list[PullRequestEvent] = []

    def disabled(event: PullRequestEvent) -> bool:
        checked.append(event)
        return False

    def client_factory(_installation_id: str) -> FakeInstallationClient:
        raise AssertionError("disabled rollout must not construct a GitHub client")

    def model_resolver() -> _RoutedRecordedModel:
        raise AssertionError("disabled rollout must not resolve a model")

    handler = build_review_handler(
        client_factory=client_factory,
        model_resolver=model_resolver,
        config=ReviewHandlerConfig(dry_run=False),
        rollout_checker=disabled,
    )
    result = handler(_claimed_job(_payload()))
    assert checked and checked[0].owner == _OWNER
    assert result == {
        "handled": True,
        "job_type": "github.pull_request",
        "review_skipped": True,
        "reason": "review_rollout_disabled",
        "repo_full_name": "acme/widgets",
        "pr_number": _PR_NUMBER,
        "head_sha": _HEAD_SHA,
        "posted": False,
        "dry_run": False,
        "installation_id": _INSTALLATION_ID,
    }
    assert "review_mode" not in result


def test_build_review_registry_registers_pull_request_handler() -> None:
    client = _full_repo_client(CONTRADICTION_DIFF)
    registry = build_review_registry(
        client_factory=lambda installation_id: client,
        model_resolver=lambda: _RoutedRecordedModel(),
        config=ReviewHandlerConfig(dry_run=True),
    )
    assert registry.job_types() == (
        "github.pull_request",
        "github.pull_request_review",
        "github.pull_request_review_comment",
    )
    handler = registry.resolve("github.pull_request")
    assert handler is not None
    result = handler(_claimed_job(_payload()))
    assert result["finding_count"] == 1


def test_build_review_registry_optionally_registers_issue_comment() -> None:
    def stub(job: ClaimedJob) -> Mapping[str, Any]:
        return {"handled": True, "job_type": job.job_type}

    registry = build_review_registry(
        client_factory=lambda installation_id: _full_repo_client(),
        model_resolver=lambda: _RoutedRecordedModel(),
        issue_comment_handler=stub,
    )
    assert registry.job_types() == (
        "github.issue_comment",
        "github.pull_request",
        "github.pull_request_review",
        "github.pull_request_review_comment",
    )


def test_default_registry_still_builds_alongside_review_registry() -> None:
    """The Stage 1 stub registry is not deleted — both coexist."""

    from cortex.hosted.worker import ArrivalRecorder, build_default_registry

    recorder = ArrivalRecorder(conn=object(), tenant_id=None, source_id=None)  # type: ignore[arg-type]
    registry = build_default_registry(recorder)
    assert registry.job_types() == (
        "github.issue_comment",
        "github.pull_request",
        "github.pull_request_review",
        "github.pull_request_review_comment",
    )


def test_build_worker_registry_chooses_by_github_app_credentials() -> None:
    from cortex.hosted.worker import ArrivalRecorder, build_worker_registry

    recorder = ArrivalRecorder(conn=object(), tenant_id=None, source_id=None)  # type: ignore[arg-type]
    # No credentials -> Stage 1 stub registry.
    stub = build_worker_registry(recorder=recorder, environ={})
    assert "github.issue_comment" in stub.job_types()
    # Credentials present -> Stage 2 review registry (one handler).
    # A placeholder PEM that satisfies GithubAppConfig's "-----BEGIN" check
    # without being a real key (the secret scanners would flag a real header).
    fake_pem = "-----BEGIN " + "PLACEHOLDER TEST KEY-----\nnot-a-real-key\n"
    review = build_worker_registry(
        recorder=recorder,
        environ={"GITHUB_APP_ID": "123", "GITHUB_APP_PRIVATE_KEY": fake_pem},
    )
    assert review.job_types() == (
        "github.installation",
        "github.installation_repositories",
        "github.issue_comment",
        "github.pull_request",
        "github.pull_request_review",
        "github.pull_request_review_comment",
    )


# ---------------------------------------------------------------------------
# ReviewAccounting.from_outcome: the one evaluator -> disclosure mapping
# ---------------------------------------------------------------------------


def _evaluate_full_repo(
    diff: str,
    findings_for: Callable[[EvaluateRequest], tuple[FindingDraft, ...]],
    *,
    token_budget: int = 8000,
) -> Any:
    """Run evaluate_review over the canned repo with a scripted model."""

    from cortex.commands.review import evaluate_review

    event = parse_pull_request_payload(_payload())
    client = _full_repo_client(diff)
    sources = stateless_review.fetch_decision_sources(client, event, ReviewHandlerConfig())
    decisions = stateless_review.derive_fixture_decisions(
        sources, event, source_timestamp=_FIXED_TIME
    )
    pack = stateless_review.build_review_pack(decisions, event, diff)
    return evaluate_review(
        pack=pack,
        diff_text=diff,
        model=_CapturingEvaluateModel(findings_for),
        token_budget=token_budget,
        tenant_id=event.tenant_id,
        source_id=event.source_id,
    )


def test_from_outcome_maps_shadow_captures_to_unconfirmed_twin_count() -> None:
    from cortex.hosted.github_comment import ReviewAccounting

    def _shadow(request: EvaluateRequest) -> tuple[FindingDraft, ...]:
        candidate = next(
            item
            for item in request.candidate_pack.candidates
            if "file contract" in item.decision_text
        )
        return (
            FindingDraft(
                finding_class=FindingClass.CITES_MISSING_PATH,
                decision_node_id=candidate.decision_node_id,
                cited_span_hashes=tuple(span.span_hash for span in candidate.cited_spans),
                summary=(
                    "The diff imports src/widgets/missing_helper.py, which does "
                    "not exist in the changed surface."
                ),
                confidence_label="advisory",
            ),
        )

    outcome = _evaluate_full_repo(CONTRADICTION_DIFF, _shadow)
    accounting = ReviewAccounting.from_outcome(outcome)
    assert accounting.unconfirmed_twin_count == outcome.shadow_finding_count
    assert accounting.unconfirmed_twin_count >= 1
    assert accounting.suppressed_below_floor == outcome.suppressed_below_floor


def test_from_outcome_surfaces_model_omitted_as_degraded_reason() -> None:
    from cortex.hosted.github_comment import ReviewAccounting

    # A token budget of 1 forces the single packed decision to be omitted for
    # budget; from_outcome carries that count into the disclosure.
    outcome = _evaluate_full_repo(CONTRADICTION_DIFF, _no_findings, token_budget=1)
    accounting = ReviewAccounting.from_outcome(outcome)
    assert accounting.omitted_for_budget == outcome.omitted_for_budget
    assert accounting.omitted_for_budget >= 1


# ---------------------------------------------------------------------------
# Config + constant invariants
# ---------------------------------------------------------------------------


def test_config_defaults_to_dry_run() -> None:
    assert ReviewHandlerConfig().dry_run is True


def test_config_rejects_non_positive_budget() -> None:
    with pytest.raises(StatelessReviewError):
        ReviewHandlerConfig(token_budget=0)


def test_config_rejects_empty_instruction_paths() -> None:
    with pytest.raises(StatelessReviewError):
        ReviewHandlerConfig(agent_instruction_paths=())


def test_duplicated_constants_match_cortex_review() -> None:
    """The module-level constants duplicated to break the import cycle agree."""

    from cortex.commands.review import (
        DEFAULT_REVIEW_TOKEN_BUDGET as REVIEW_BUDGET,
    )
    from cortex.commands.review import (
        MODEL_FIXTURES_ENV_VAR as REVIEW_ENV,
    )

    assert stateless_review.MODEL_FIXTURES_ENV_VAR == REVIEW_ENV
    assert stateless_review.DEFAULT_REVIEW_TOKEN_BUDGET == REVIEW_BUDGET


def test_repo_scoped_ids_are_deterministic_and_repo_specific() -> None:
    a = PullRequestEvent(
        installation_id="1",
        owner="acme",
        repo="widgets",
        pr_number=1,
        base_sha="a" * 7,
        head_sha="b" * 7,
    )
    a_again = PullRequestEvent(
        installation_id="9",
        owner="acme",
        repo="widgets",
        pr_number=2,
        base_sha="c" * 7,
        head_sha="d" * 7,
    )
    b = PullRequestEvent(
        installation_id="1",
        owner="acme",
        repo="gadgets",
        pr_number=1,
        base_sha="a" * 7,
        head_sha="b" * 7,
    )
    # Same repo -> same tenant/source UUID regardless of PR/installation.
    assert a.tenant_id == a_again.tenant_id
    assert a.source_id == a_again.source_id
    # Different repo -> different identity.
    assert a.tenant_id != b.tenant_id
