"""Hosted Cortex substrate boundaries.

The hosted package is intentionally separate from the `.cortex/` file-format
CLI. Hosted code may project local Cortex files into Postgres, but the protocol
and CLI remain usable without hosted services.
"""

from cortex.hosted.ask_ledger import (
    ASK_LEDGER_RETRIEVAL_CONFIG_VERSION,
    RRF_K,
    SOURCE_WEIGHTS,
    AnswerState,
    AskLedgerCandidate,
    AskLedgerQuery,
    AskLedgerValidationError,
    CandidateSource,
    CitedContextPack,
    CitedSourceSpan,
    RetrievalTrace,
    SourceRank,
    ask_ledger_retrieval_sql,
    build_ask_ledger_context_pack,
    build_cited_context_pack,
    reciprocal_rank_fusion,
    retrieval_trace_insert_sql,
)
from cortex.hosted.decisions_for_diff import (
    DECISIONS_FOR_DIFF_RETRIEVAL_CONFIG_VERSION,
    DEFAULT_DECISIONS_FOR_DIFF_LIMIT,
    MAX_DECISIONS_FOR_DIFF_LIMIT,
    DecisionsForDiffCandidate,
    DecisionsForDiffCandidatePack,
    DecisionsForDiffQuery,
    DecisionsForDiffValidationError,
    build_decisions_for_diff_candidate_pack,
    decisions_for_diff_retrieval_sql,
)
from cortex.hosted.ledger_events import (
    ActorRef,
    LedgerEvent,
    LedgerEventType,
    LedgerEventValidationError,
    derive_idempotency_key,
    ledger_event_insert_sql,
)
from cortex.hosted.provenance import (
    ProvenanceValidationError,
    SourceDocument,
    SourceSpan,
    content_hash,
    source_document_insert_sql,
    source_span_insert_sql,
)
from cortex.hosted.schema import HOSTED_SCHEMA_VERSION, create_schema_sql
from cortex.hosted.scopes import (
    SEMANTIC_MATCH_WEIGHT,
    STRUCTURAL_SCOPE_WEIGHTS,
    ChangedSurface,
    DecisionScope,
    QueryScope,
    ScopeType,
    ScopeValidationError,
    decision_scope_insert_sql,
    decisions_for_diff_scope_sql,
    normalize_scope_value,
    query_scope_parameters,
    scope_reason_code,
)
from cortex.hosted.storage import (
    CANONICAL_HOSTED_STORE,
    REBUILDABLE_SQLITE_CACHE_ROLES,
    StoreBoundaryError,
    validate_canonical_store,
    validate_rebuildable_cache_store,
)

__all__ = [
    "ASK_LEDGER_RETRIEVAL_CONFIG_VERSION",
    "CANONICAL_HOSTED_STORE",
    "DECISIONS_FOR_DIFF_RETRIEVAL_CONFIG_VERSION",
    "DEFAULT_DECISIONS_FOR_DIFF_LIMIT",
    "HOSTED_SCHEMA_VERSION",
    "MAX_DECISIONS_FOR_DIFF_LIMIT",
    "REBUILDABLE_SQLITE_CACHE_ROLES",
    "RRF_K",
    "SEMANTIC_MATCH_WEIGHT",
    "SOURCE_WEIGHTS",
    "STRUCTURAL_SCOPE_WEIGHTS",
    "ActorRef",
    "AnswerState",
    "AskLedgerCandidate",
    "AskLedgerQuery",
    "AskLedgerValidationError",
    "CandidateSource",
    "ChangedSurface",
    "CitedContextPack",
    "CitedSourceSpan",
    "DecisionScope",
    "DecisionsForDiffCandidate",
    "DecisionsForDiffCandidatePack",
    "DecisionsForDiffQuery",
    "DecisionsForDiffValidationError",
    "LedgerEvent",
    "LedgerEventType",
    "LedgerEventValidationError",
    "ProvenanceValidationError",
    "QueryScope",
    "RetrievalTrace",
    "ScopeType",
    "ScopeValidationError",
    "SourceDocument",
    "SourceRank",
    "SourceSpan",
    "StoreBoundaryError",
    "ask_ledger_retrieval_sql",
    "build_ask_ledger_context_pack",
    "build_cited_context_pack",
    "build_decisions_for_diff_candidate_pack",
    "content_hash",
    "create_schema_sql",
    "decision_scope_insert_sql",
    "decisions_for_diff_retrieval_sql",
    "decisions_for_diff_scope_sql",
    "derive_idempotency_key",
    "ledger_event_insert_sql",
    "normalize_scope_value",
    "query_scope_parameters",
    "reciprocal_rank_fusion",
    "retrieval_trace_insert_sql",
    "scope_reason_code",
    "source_document_insert_sql",
    "source_span_insert_sql",
    "validate_canonical_store",
    "validate_rebuildable_cache_store",
]
