"""Committed recorded evaluate responses for the simlab scenarios (#521).

CI replays every scenario against ``recordings/simlab-recordings.json`` via
``RecordedResponsePlayer`` — zero live model calls, and a replay miss is a
hard, named failure. The recording is generated by this module's own
generator through the one pipeline path (``runner.run_scenario`` with the
scripted ground-truth model teed through ``RecordingEvaluateModel``), so the
recorded ``input_hash`` contract can never quietly disagree with the
runner; the drift-guard test regenerates the bytes and compares.

Re-record after changing specs, extractor behavior, or the evaluate prompt:

    uv run python -m tests.simlab.recordings
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from cortex.hosted.eval_fixtures import EvalFixture
from cortex.hosted.model_interfaces import EvaluateModel
from cortex.hosted.recorded_responses import (
    RecordedResponsePlayer,
    RecordingEvaluateModel,
    ResponseRecorder,
)
from tests.simlab.runner import ScriptedEvaluateModel, run_scenario, verify_scenario
from tests.simlab.specs import (
    SIMLAB_DIR,
    ScenarioSpec,
    load_archetype_specs,
    load_scenario_specs,
)

RECORDINGS_PATH = SIMLAB_DIR / "recordings" / "simlab-recordings.json"

# Caller-supplied recording timestamp (the recorded-response store never
# reads a clock): fixed so regeneration is byte-identical.
SIMLAB_RECORDED_AT = "2026-06-10T00:00:00+00:00"


def generate_recordings_json(work_dir: Path) -> str:
    """Run every committed scenario with the scripted model; return the store.

    Every scenario run is verified against its own spec before the recording
    is trusted — a generator that records an expectation-violating run would
    bake the violation into CI as truth.
    """

    archetypes = load_archetype_specs()
    scenarios = load_scenario_specs()
    recorder = ResponseRecorder(
        fixture_path=work_dir / "simlab-recordings.json",
        recorded_at=SIMLAB_RECORDED_AT,
    )

    def recording_player(scenario: ScenarioSpec, fixture: EvalFixture) -> EvaluateModel:
        _ = fixture
        return RecordingEvaluateModel(ScriptedEvaluateModel(scenario), recorder)

    for scenario in scenarios:
        result = run_scenario(
            scenario,
            archetypes[scenario.archetype_id],
            player_factory=recording_player,
            work_dir=work_dir / "repos",
        )
        verify_scenario(result)
    return recorder.store.to_canonical_json()


def load_recorded_player() -> RecordedResponsePlayer:
    """The committed-recording player CI scenarios replay through."""

    return RecordedResponsePlayer.load(RECORDINGS_PATH)


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="simlab-recordings-") as tmp:
        text = generate_recordings_json(Path(tmp))
    RECORDINGS_PATH.parent.mkdir(parents=True, exist_ok=True)
    RECORDINGS_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {RECORDINGS_PATH}")


if __name__ == "__main__":
    main()
